# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2.22-apache-node-browsers
      - image: circleci/mysql:5.7.19
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db

    steps:
      - checkout

      - run: 
          name: Install PHP extensions
          command: |
            sudo apt update
            sudo docker-php-ext-install zip mysqli json

      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Composer Install
          command: |
            composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-
      - run: yarn install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Set environment
          command: |
            sudo cp env.ini.circle config/env.ini

      - run:
          name: Prepare Database
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u root -prootpw test_db < storage/sql/users.sql

      - run:
          name: Check PHP Convention
          command: |
            ./vendor/bin/phpmd app text phpmd.xml
            ./vendor/bin/phpcs -n -d memory_limit=-1 --standard=phpcs.xml

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit tests
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

workflows:
  version: 2
  demo_ci_test:
    jobs:
      - build
